// <auto-generated>
//     This file is generated by a tool.
// </auto-generated>

namespace Genco.Example
{
    /// <summary>
    /// This is a generated class.
    /// The tool used to generate this file is called Genco.
    /// </summary>
    public readonly record struct MyModel
    {
        

    }
}